### ISSUE TITLE
Error: unknown command 'ndpull'

### ISSUE THREAD

**Issue by isle9** [evilmanimani/beets-navidrome_sync#5]
I'm getting this in the terminal when running either `beet ndpull` or `beet import`:

```** error loading plugin navidrome_sync:
Traceback (most recent call last):
  File "~/.local/pipx/venvs/beets/lib/python3.11/site-packages/beets/plugins.py", line 269, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/pipx/venvs/beets/lib/python3.11/site-packages/beetsplug/navidrome_sync/__init__.py", line 3, in <module>
    from . import sftpuploader
  File "~/.local/pipx/venvs/beets/lib/python3.11/site-packages/beetsplug/navidrome_sync/sftpuploader.py", line 1, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'

error: unknown command 'ndpull'```

**Comment by isle9** [comment]
Unfortunately, I'm still getting 'error: unknown command 'ndpull' even after sorting the dependencies.
