### ISSUE TITLE
sqlite3.OperationalError: no such column: mbz_track_id

### ISSUE THREAD

**Issue by isle9** [evilmanimani/beets-navidrome_sync#6]
```
This is a destructive operation, please make sure you have a backup of your Navidrome DB before continuing. Press enter to continue...
Traceback (most recent call last):
  File "~/.local/bin/beet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/pipx/venvs/beets/lib/python3.11/site-packages/beets/ui/__init__.py", line 1862, in main
    _raw_main(args)
  File "~/.local/pipx/venvs/beets/lib/python3.11/site-packages/beets/ui/__init__.py", line 1849, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "~/.spotdl/beets-navidrome_sync-main/beetsplug/navidrome_sync.py", line 126, in nd_sync
    self.nd_pull(lib, conn, cur)
  File "~/.spotdl/beets-navidrome_sync-main/beetsplug/navidrome_sync.py", line 343, in nd_pull
    for (item_id, artist, albumArtist, album, title, mb_trackid) in cur.execute('SELECT id, artist, album_artist, album, title, mbz_track_id FROM media_file;'):
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: mbz_track_id
```

**Comment by evilmanimani** [comment]
Can you confirm which specific command and the parameters used which returned that error? Thanks.

**Comment by isle9** [comment]
Both `beet ndpull` and `beet ndpush` give the same error.

**Comment by evilmanimani** [comment]
Looks like mbz_track_id was renamed to mbz_recording_id in the navidrome database, so yeah, should work now if you grab that most recent version. Works for me at least, let me know how it goes.

**Comment by isle9** [comment]
I kinda guessed that it was probably something like that. Tried looking around a bit, but I wasn't able to find anything. I'll try it tomorrow (currently importing my library).

**Comment by isle9** [comment]
Works for me too now!
